version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: restaurant_app_postgres_container
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: restaurant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sampada@3005
    volumes:
      - /Users/sampadadeshmukh/Desktop/restaurant_volume:/var/lib/postgresql/data

  springbootapp:
    build: .
    image: restaurant_app_image
    container_name:  restaurant_app_container
    restart: always
    ports:
      - "8080:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/restaurant_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Sampada@3005

volumes:
  postgres_data:
